delete from TB_UF;  
delete from TB_USUARIO;

insert into TB_UF(ID_UF, SIGLA, NOME) Values(12,'AC','Acre');  
insert into TB_UF(ID_UF, SIGLA, NOME) Values(27,'AL','Alagoas');  
insert into TB_UF(ID_UF, SIGLA, NOME) Values(13,'AM','Amazonas');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(16,'AP','Amapá');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(29,'BA','Bahia');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(23,'CE','Ceará');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(53,'DF','Distrito Federal');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(32,'ES','Espírito Santo');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(52,'GO','Goiás');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(21,'MA','Maranhão');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(31,'MG','Minas Gerais');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(50,'MS','Mato Grosso do Sul');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(51,'MT','Mato Grosso');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(15,'PA','Pará');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(25,'PB','Paraíba');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(26,'PE','Pernambuco');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(22,'PI','Piauí');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(41,'PR','Paraná');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(33,'RJ','Rio de Janeiro');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(24,'RN','Rio Grande do Norte');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(11,'RO','Rondônia');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(14,'RR','Roraima');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(43,'RS','Rio Grande do Sul');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(42,'SC','Santa Catarina');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(28,'SE','Sergipe');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(35,'SP','São Paulo');
insert into TB_UF(ID_UF, SIGLA, NOME) Values(17,'TO','Tocantins');
